// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/demo": {
    params: {};
  };
  "/formats": {
    params: {};
  };
  "/:locale": {
    params: {
      "locale": string;
    };
  };
  "/:locale/demo": {
    params: {
      "locale": string;
    };
  };
  "/:locale/formats": {
    params: {
      "locale": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/demo" | "/formats" | "/:locale" | "/:locale/demo" | "/:locale/formats" | "/robots.txt" | "/sitemap.xml" | "/*";
  };
  "routes/choose.tsx": {
    id: "routes/choose";
    page: "/";
  };
  "routes/unprefixed.tsx": {
    id: "choose/demo";
    page: "/demo";
  } | {
    id: "choose/formats";
    page: "/formats";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/:locale";
  };
  "routes/demo.tsx": {
    id: "routes/demo";
    page: "/:locale/demo";
  };
  "routes/formats.tsx": {
    id: "routes/formats";
    page: "/:locale/formats";
  };
  "routes/robots.ts": {
    id: "routes/robots";
    page: "/robots.txt";
  };
  "routes/sitemap.ts": {
    id: "routes/sitemap";
    page: "/sitemap.xml";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/choose": typeof import("./app/routes/choose.tsx");
  "choose/demo": typeof import("./app/routes/unprefixed.tsx");
  "choose/formats": typeof import("./app/routes/unprefixed.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/demo": typeof import("./app/routes/demo.tsx");
  "routes/formats": typeof import("./app/routes/formats.tsx");
  "routes/robots": typeof import("./app/routes/robots.ts");
  "routes/sitemap": typeof import("./app/routes/sitemap.ts");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};